### ISSUE TITLE
Table is randomly ordered.

### ISSUE THREAD

**Issue by frakman1** [AishPratap/APSGroupedTableView#1] opened 2017-09-11 04:36 UTC
How do I display the grouped table in the order it was created in `mockData()`? The order is currently random. I think it has something to do with this line:
        let keys = Array(tableData.keys)

By the way, what does this mean:
[String:Array<String>]

**Comment by frakman1** [comment] 2017-09-11 15:45
I was able to at least sort it alphabetically by replacing the two instances of the line:

`        let keys = Array(tableData.keys)`

with:

`        let keys = Array(tableData.keys).sorted(by: <)`

in `ViewController.swift`

I would still prefer to have it ordered in the order I created the entries. Is that possible?

**Comment by AishPratap** [comment] 2017-09-13 05:13
Hey @frakman1 , so the issue is not with the component. The dataset created in the mockdata() function uses a dictionary. A dictionary in iOS is an unordered set of data containing key value pairs. That's the reason why the order changes from the way you insert it to the way it is produced. 

Also to answer your other question, [String: Array] is basically defining a dictionary. You can read more about this here:

[Collection types in iOS](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/CollectionTypes.html#//apple_ref/doc/uid/TP40014097-CH8-ID113)

Closing the issue as the issue is not with the component.

**Closed as completed by AishPratap** 2017-09-13 05:13 UTC
Labels: invalid

**Comment by frakman1** [comment] 2017-09-17 17:55
That is such a cop out. You **_decided_** to implement it as a dictionary. The issue is with a **_feature_** of this grouped table. The issue is that is can't be displayed in the order the user wants it to be.
It is **_not_** invalid and sticking an `invalid` label on an issue doesn't make it so.

**Comment by AishPratap** [comment] 2017-09-17 19:13
@frakman1 !!! With all due respect, there is no issue with the component. What you are referring to is the demo of the component being used. I decided to use a dictionary to mock data there because I did want the users to see how this would look in a realistic situation. This is not a bug. You can very well implement the data source using an array, in which case, it would work perfectly fine. Again, that is beyond the scope of this component. How you implement the data source is your design decision.

It is similar to UITableViewController. Even if you use a dictionary to feed the data to it, it will not maintain the order.

**Comment by frakman1** [comment] 2017-09-17 22:25
You are correct. I hereby withdraw my earlier objection.
